/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krono
 */
public class GUIProyectoFinal extends javax.swing.JFrame {
//Para contar cuantas veces se van ingresando los registros de cada tabla.

    String elements = "";
    int sumaTotal = 0;
    Vendedor vendedorUno;
    Vendedor vendedorDos;
    Vendedor vendedorTres;
    int vendAleatorio;
    double precioProducto = 0;
    int numeroEjecuciones = 0;
    int coincidencias[] = {99, 99, 99, 99, 99};
    int precios[] = {99, 99, 99, 99, 99};
    boolean isMatched;
    boolean hasRows;
    int elementosComprados = 0;
    Vendedor vendedores[];
    //Declaramos los arreglos para cada tabla.*/
    ArrayList<Mercaderia> productos;
    ArrayList<String> nombreProductos;
    ArrayList<String> tipoProductos;
    ArrayList<Mercaderia> carrito;
    //Declarar los modelos de cada tabla
    DefaultTableModel dtmModeloTablaUno;
    Cliente client;

    //Esta funcion deshabilita los componentes de un panel
    public static void disableComponents(Container panelName) {
        for (Component component : panelName.getComponents()) {
            component.setEnabled(false);
        }
    }
// Esta hace lo contrario

    public static void enableComponents(Container panelName) {
        for (Component component : panelName.getComponents()) {
            component.setEnabled(true);
        }
    }

    /**
     * Creates new form GUIProyectoFinal
     */
    public GUIProyectoFinal() {
        initComponents();
        txtPrecioCompra.setEditable(false);
        disableComponents(pnlAdmin);
        disableComponents(pnlCliente);
        disableComponents(pnlMer);
        carrito = new ArrayList<>();
        productos = new ArrayList<>();
        nombreProductos = new ArrayList<>();
        tipoProductos = new ArrayList<>();
        dtmModeloTablaUno = new DefaultTableModel();
        dtmModeloTablaUno.addColumn("Nombre");
        dtmModeloTablaUno.addColumn("Tipo");
        dtmModeloTablaUno.addColumn("Codigo");
        dtmModeloTablaUno.addColumn("Cantidad");
        dtmModeloTablaUno.addColumn("Precio");
        tblInventario.setModel(dtmModeloTablaUno);
        vendedores = new Vendedor[3];
        vendedores[0] = new Vendedor(178459278, "EMP-001", "Almendro", "Pedrerlol");
        vendedores[1] = new Vendedor(172346863, "EMP-002", "Juana", "Caicho");
        vendedores[2] = new Vendedor(147845198, "EMP-003", "Magerly", "Chavez");

    }

    public void adminCleaner() {

        txtNombreProducto.setText("");
        txtCodigo.setText("");
        txtCosto.setText("");
        txtUnidad.setText("");
        cmbProducto.setSelectedItem(null);

    }

    public void clientCleaner() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtRUC.setText("");
        cmbProductoCompra.setSelectedItem(null);
        txtCantidaCompra.setText("");
        txtPrecioCompra.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbtCliente = new javax.swing.JRadioButton();
        rbtPersonal = new javax.swing.JRadioButton();
        pnlAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        lblProducto = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JTextField();
        btnGuardarCambios = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        lblNombreP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        pnlCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbProductoCompra = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCantidaCompra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setText("Bienvenido");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel3.setText("Seleccione el tipo de usuario: ");

        btgTipo.add(rbtCliente);
        rbtCliente.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        rbtCliente.setText("Cliente");
        rbtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtClienteActionPerformed(evt);
            }
        });

        btgTipo.add(rbtPersonal);
        rbtPersonal.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        rbtPersonal.setText("Personal Administrativo");
        rbtPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPersonalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel1.setText("Inventario");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setText("Agregar nueva mercancía");

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Computador", "Celular" }));
        cmbProducto.setSelectedIndex(-1);
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });

        lblProducto.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblProducto.setText("Tipo Producto");

        lblCodigo.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblCodigo.setText("Código");

        lblCosto.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblCosto.setText("Costo");

        lblUnidad.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblUnidad.setText("Unidades");

        txtUnidad.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtUnidadComponentHidden(evt);
            }
        });
        txtUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadActionPerformed(evt);
            }
        });

        btnGuardarCambios.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        lblNombreP.setText("Nombre:");

        javax.swing.GroupLayout pnlMerLayout = new javax.swing.GroupLayout(pnlMer);
        pnlMer.setLayout(pnlMerLayout);
        pnlMerLayout.setHorizontalGroup(
            pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMerLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(pnlMerLayout.createSequentialGroup()
                        .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProducto)
                            .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreP)
                                .addComponent(lblCodigo)))
                        .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMerLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCosto)
                            .addComponent(lblUnidad))))
                .addGap(26, 26, 26)
                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarCambios)
                .addContainerGap())
        );
        pnlMerLayout.setVerticalGroup(
            pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto)
                    .addComponent(lblCosto)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidad)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreP))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tblInventario.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInventario.setEnabled(false);
        jScrollPane1.setViewportView(tblInventario);

        btnConsultar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btnConsultar.setText("Consultar Inventario");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addComponent(pnlMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(249, 249, 249))))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnConsultar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar)
                .addGap(11, 11, 11))
        );

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setText("Facturación");

        lblNombre.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblApellido.setText("Apellido:");

        lblRUC.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblRUC.setText("RUC:");

        jLabel13.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel13.setText("Comprar");

        cmbProductoCompra.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel14.setText("Producto:");

        jLabel15.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel15.setText("Cantidad");

        jLabel16.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel16.setText("Precio");

        btnAgregar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGenerar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btnGenerar.setText("Generar factura");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(144, 144, 144))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(107, 107, 107))
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16))
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRUC)
                                    .addComponent(jLabel14))
                                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlClienteLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmbProductoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregar)
                                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCantidaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnlClienteLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRUC)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtCantidaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(44, 44, 44)
                .addComponent(btnGenerar)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(rbtPersonal)
                .addGap(121, 121, 121)
                .addComponent(rbtCliente)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbtCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtPersonal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadActionPerformed

    private void txtUnidadComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtUnidadComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadComponentHidden

    private void rbtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtClienteActionPerformed
        disableComponents(pnlAdmin);
        disableComponents(pnlMer);
        enableComponents(pnlCliente);
        if (nombreProductos.size() > 0) {
            cmbProductoCompra.removeAllItems();
            for (int insert = 0; insert < nombreProductos.size(); insert++) {

                cmbProductoCompra.addItem(nombreProductos.get(insert));
            }
        }
        cmbProductoCompra.setSelectedIndex(-1);


    }//GEN-LAST:event_rbtClienteActionPerformed

    private void rbtPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPersonalActionPerformed
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Ingrese la contraseña:");
        JPasswordField pass = new JPasswordField(4);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancelar"};

        JOptionPane.showOptionDialog(null, panel, "Personal Administrativo",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        System.out.println(pass.getClass());
        System.out.println(pass.getPassword());
        String contra = String.valueOf(pass.getPassword());
        System.out.println("Impressing the password " + contra);
        if (!String.valueOf(pass.getPassword()).equals("1234")) {
            JOptionPane.showMessageDialog(rootPane, "BAD");
            btgTipo.clearSelection();
        } else {
            System.out.println("QUE PASA!");
            enableComponents(pnlAdmin);
            enableComponents(pnlMer);
            disableComponents(pnlCliente);
            clientCleaner();
        }

    }//GEN-LAST:event_rbtPersonalActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed

        boolean codigoValido;
        switch (txtCodigo.getText()) {
            case "LIB-":
            case "COM-":
            case "TLF-":
                codigoValido = false;
                break;
            default:
                codigoValido = true;
        }

        if (cmbProducto.getSelectedItem().equals("") || txtCodigo.getText().equals("") || txtCodigo.getText().length() != 7
                || txtCosto.getText().equals("") || txtUnidad.getText().equals("") || !codigoValido
                || txtNombreProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "¡Algo no ha ido como se esperaba!");
        } else {
            System.out.println(cmbProducto.getSelectedItem().toString());
            isMatched = false;
            int k = 0;
            System.out.println(nombreProductos.size());
            System.out.println(tipoProductos.size());
            if (numeroEjecuciones > 0) {
                if (nombreProductos.contains(txtNombreProducto.getText())) {
                    System.out.println("\n Checking types of productos\n\n");
                    for (int j = 0; j < nombreProductos.size(); j++) {
                        if (nombreProductos.get(j).equals(txtNombreProducto.getText()) && tipoProductos.get(j).equals(cmbProducto.getSelectedItem().toString())) {
                            System.out.println("PAREÇE HABER MATCH CON: " + nombreProductos.get(j));
                            System.out.println("De tipos... " + tipoProductos.get(j));
                            coincidencias[k] = j;
                            k++;
                        }
                        System.out.println("---------------------------------------------------------------------");
                    }
                }

                System.out.println("\t\t::::Verificando coincidencias::::\n");
                for (int con = 0; con < 5; con++) {
                    if (coincidencias[con] != 99) {
                        isMatched = true;
                        nombreProductos.set(coincidencias[con], txtNombreProducto.getText());

                        tipoProductos.set(coincidencias[con], cmbProducto.getSelectedItem().toString());

                        System.out.println("\t\t::::Se ha encontrado match::::" + productos.get(coincidencias[con]).toString() + "\n");

                        productos.set(coincidencias[con], new Mercaderia(txtNombreProducto.getText(), Integer.parseInt(txtCodigo.getText().substring(4)),
                                productos.get(coincidencias[con]).getCantidad() + Integer.parseInt(txtUnidad.getText()), Double.parseDouble(txtCosto.getText())));
                        coincidencias[con] = 99;
                    }
                }
                if (!isMatched) {
                    productos.add(new Mercaderia(txtNombreProducto.getText(), Integer.parseInt(txtCodigo.getText().substring(4)),
                            Integer.parseInt(txtUnidad.getText()), Double.parseDouble(txtCosto.getText())));
                    nombreProductos.add(txtNombreProducto.getText());
                    tipoProductos.add(cmbProducto.getSelectedItem().toString());
                }
                System.out.println("Imprimiendo la lista de productos");
                productos.forEach(me -> {
                    System.out.println(me);
                });

                System.out.println("Imprimiendo los nombres de productos");
                nombreProductos.forEach(np -> {
                    System.out.println(np);
                });
            } else {
                nombreProductos.add(txtNombreProducto.getText());
                tipoProductos.add(cmbProducto.getSelectedItem().toString());
                productos.add(new Mercaderia(txtNombreProducto.getText(), Integer.parseInt(txtCodigo.getText().substring(4)),
                        Integer.parseInt(txtUnidad.getText()), Double.parseDouble(txtCosto.getText())));
            }
            for (int it = 0; it < 5; it++) {
                System.out.println(coincidencias[it]);
            }
            adminCleaner();
            numeroEjecuciones++;

        }


    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        try {
            switch (cmbProducto.getSelectedItem().toString()) {
                case "Libro":
                    txtCodigo.setText("LIB-");
                    break;
                case "Computador":
                    txtCodigo.setText("COM-");
                    break;
                case "Celular":
                    txtCodigo.setText("TLF-");
                    break;
            }
        } catch (Exception e) {
            System.out.println("I cover it!");
            System.out.println("---------------------------------------------------");
        }

    }//GEN-LAST:event_cmbProductoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (hasRows) {
            for (int l = 0; l < dtmModeloTablaUno.getRowCount(); l++) {
                dtmModeloTablaUno.removeRow(l);
                l -= 1;
            }
            hasRows = false;
        }

        for (int l = 0; l < productos.size(); l++) {
            dtmModeloTablaUno.addRow(new Object[]{productos.get(l).getNombre(), tipoProductos.get(l), productos.get(l).getCodigo(),
                productos.get(l).getCantidad(), productos.get(l).getPrecio()});
            hasRows = true;
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtRUC.getText().equals("")
                || cmbProductoCompra.getSelectedIndex() == -1 || txtCantidaCompra.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "¡Algo no ha ido como se esperaba!");
        } else {
            int x = 0;
            System.out.println(cmbProductoCompra.getSelectedItem().toString().substring(0, 2));
            if (nombreProductos.contains(cmbProductoCompra.getSelectedItem().toString())) {
                System.out.println("\n Checking types of productos\n\n");

                for (int j = 0; j < nombreProductos.size(); j++) {
                    if (nombreProductos.get(j).equals(cmbProductoCompra.getSelectedItem().toString().substring(0, 2))) {
                        System.out.println("ENCONTRADO!!: " + nombreProductos.get(j));
                        System.out.println("De tipos... " + tipoProductos.get(j));
                        precios[x] = j;
                        x++;
                    }
                    System.out.println("---------------------------------------------------------------------");
                }
            }

            System.out.println("\t\t::::Verificando coincidencias::::\n");
            for (int con = 0; con < 5; con++) {
                if (precios[con] != 99) {
                    productos.set(precios[con], new Mercaderia(productos.get(precios[con]).getNombre(), productos.get(precios[con]).getCodigo(),
                            productos.get(precios[con]).getCantidad() - Integer.parseInt(txtCantidaCompra.getText()), productos.get(precios[con]).getPrecio()));

                    carrito.add(productos.get(precios[con]));

                    elementosComprados++;
                    System.out.println(precioProducto);
                    precios[con] = 99;

                }
            }
        

        Control controlador = new Control();
        txtPrecioCompra.setText(String.valueOf(controlador.precioPorProducto(Integer.parseInt(txtCantidaCompra.getText()), precioProducto)));
        client = new Cliente(Integer.parseInt(txtRUC.getText()), txtNombre.getText(), txtApellido.getText());
        vendAleatorio = (int) (Math.random() * 3) + 1;
        System.out.println(elementosComprados);
        System.out.println(carrito.size());
        for (int y = 0; y < carrito.size(); y++) {
            elements += "Concepto producto " + y + ": " + carrito.get(y).getNombre() + "\n"
                    + "Cantidad: " + txtCantidaCompra.getText();
            sumaTotal += carrito.get(y).getPrecio();
        }

    }

    txtCantidaCompra.setText (
            

    "");
    cmbProductoCompra.setSelectedIndex (
            
-1);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        JOptionPane.showMessageDialog(null, "Nombre: " + client.getNombre() + "\n"
                + "Apellido: " + client.getApellido() + "\n"
                + "RUC: " + client.getRUCc() + "\n" + elements + "\n valor total: "
                + sumaTotal + "\n Atendido por: " + vendedores[vendAleatorio].getNombre()
                + " " + vendedores[vendAleatorio].getApellido());
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProyectoFinal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProyectoFinal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProyectoFinal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProyectoFinal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIProyectoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbProductoCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlMer;
    private javax.swing.JRadioButton rbtCliente;
    private javax.swing.JRadioButton rbtPersonal;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCantidaCompra;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
